usr/share/java/glacier2-*.jar
usr/share/java/glacier2-*-sources.jar

usr/share/java/ice-*.jar
usr/share/java/ice-*-sources.jar

usr/share/java/icebox-*.jar
usr/share/java/icebox-*-sources.jar

usr/share/java/icediscovery-*.jar
usr/share/java/icediscovery-*-sources.jar

usr/share/java/icelocatordiscovery-*.jar
usr/share/java/icelocatordiscovery-*-sources.jar

usr/share/java/icegrid-*.jar
usr/share/java/icegrid-*-sources.jar

usr/share/java/icepatch2-*.jar
usr/share/java/icepatch2-*-sources.jar

usr/share/java/icestorm-*.jar
usr/share/java/icestorm-*-sources.jar

usr/share/maven-repo/com/zeroc/glacier2/*/glacier2-*.jar
usr/share/maven-repo/com/zeroc/glacier2/*/glacier2-*-sources.jar
usr/share/maven-repo/com/zeroc/glacier2/*/glacier2-*.pom

usr/share/maven-repo/com/zeroc/ice/*/ice-*.jar
usr/share/maven-repo/com/zeroc/ice/*/ice-*-sources.jar
usr/share/maven-repo/com/zeroc/ice/*/ice-*.pom

usr/share/maven-repo/com/zeroc/icebox/*/icebox-*.jar
usr/share/maven-repo/com/zeroc/icebox/*/icebox-*-sources.jar
usr/share/maven-repo/com/zeroc/icebox/*/icebox-*.pom

usr/share/maven-repo/com/zeroc/icediscovery/*/icediscovery-*.jar
usr/share/maven-repo/com/zeroc/icediscovery/*/icediscovery-*-sources.jar
usr/share/maven-repo/com/zeroc/icediscovery/*/icediscovery-*.pom

usr/share/maven-repo/com/zeroc/icelocatordiscovery/*/icelocatordiscovery-*.jar
usr/share/maven-repo/com/zeroc/icelocatordiscovery/*/icelocatordiscovery-*-sources.jar
usr/share/maven-repo/com/zeroc/icelocatordiscovery/*/icelocatordiscovery-*.pom

usr/share/maven-repo/com/zeroc/icegrid/*/icegrid-*.jar
usr/share/maven-repo/com/zeroc/icegrid/*/icegrid-*-sources.jar
usr/share/maven-repo/com/zeroc/icegrid/*/icegrid-*.pom

usr/share/maven-repo/com/zeroc/icepatch2/*/icepatch2-*.jar
usr/share/maven-repo/com/zeroc/icepatch2/*/icepatch2-*-sources.jar
usr/share/maven-repo/com/zeroc/icepatch2/*/icepatch2-*.pom

usr/share/maven-repo/com/zeroc/icestorm/*/icestorm-*.jar
usr/share/maven-repo/com/zeroc/icestorm/*/icestorm-*-sources.jar
usr/share/maven-repo/com/zeroc/icestorm/*/icestorm-*.pom
