usr/bin/slice2java
usr/share/man/man1/slice2java.1

usr/bin/slice2freezej
usr/share/man/man1/slice2freezej.1

usr/share/java/freeze-3.6.1.jar
usr/share/java/freeze-3.6.1-source.jar

usr/share/java/glacier2-3.6.1.jar
usr/share/java/glacier2-3.6.1-source.jar

usr/share/java/ice-3.6.1.jar
usr/share/java/ice-3.6.1-source.jar

usr/share/java/icebox-3.6.1.jar
usr/share/java/icebox-3.6.1-source.jar

usr/share/java/icediscovery-3.6.1.jar
usr/share/java/icediscovery-3.6.1-source.jar

usr/share/java/icelocatordiscovery-3.6.1.jar
usr/share/java/icelocatordiscovery-3.6.1-source.jar

usr/share/java/icegrid-3.6.1.jar
usr/share/java/icegrid-3.6.1-source.jar

usr/share/java/icepatch2-3.6.1.jar
usr/share/java/icepatch2-3.6.1-source.jar

usr/share/java/icestorm-3.6.1.jar
usr/share/java/icestorm-3.6.1-source.jar

usr/share/maven-repo/com/zeroc/freeze/3.6.1/freeze-3.6.1.jar
usr/share/maven-repo/com/zeroc/freeze/3.6.1/freeze-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/freeze/3.6.1/freeze-3.6.1.pom

usr/share/maven-repo/com/zeroc/glacier2/3.6.1/glacier2-3.6.1.jar
usr/share/maven-repo/com/zeroc/glacier2/3.6.1/glacier2-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/glacier2/3.6.1/glacier2-3.6.1.pom

usr/share/maven-repo/com/zeroc/ice/3.6.1/ice-3.6.1.jar
usr/share/maven-repo/com/zeroc/ice/3.6.1/ice-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/ice/3.6.1/ice-3.6.1.pom

usr/share/maven-repo/com/zeroc/icebox/3.6.1/icebox-3.6.1.jar
usr/share/maven-repo/com/zeroc/icebox/3.6.1/icebox-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icebox/3.6.1/icebox-3.6.1.pom

usr/share/maven-repo/com/zeroc/icediscovery/3.6.1/icediscovery-3.6.1.jar
usr/share/maven-repo/com/zeroc/icediscovery/3.6.1/icediscovery-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icediscovery/3.6.1/icediscovery-3.6.1.pom

usr/share/maven-repo/com/zeroc/icelocatordiscovery/3.6.1/icelocatordiscovery-3.6.1.jar
usr/share/maven-repo/com/zeroc/icelocatordiscovery/3.6.1/icelocatordiscovery-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icelocatordiscovery/3.6.1/icelocatordiscovery-3.6.1.pom

usr/share/maven-repo/com/zeroc/icegrid/3.6.1/icegrid-3.6.1.jar
usr/share/maven-repo/com/zeroc/icegrid/3.6.1/icegrid-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icegrid/3.6.1/icegrid-3.6.1.pom

usr/share/maven-repo/com/zeroc/icepatch2/3.6.1/icepatch2-3.6.1.jar
usr/share/maven-repo/com/zeroc/icepatch2/3.6.1/icepatch2-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icepatch2/3.6.1/icepatch2-3.6.1.pom

usr/share/maven-repo/com/zeroc/icestorm/3.6.1/icestorm-3.6.1.jar
usr/share/maven-repo/com/zeroc/icestorm/3.6.1/icestorm-3.6.1-source.jar
usr/share/maven-repo/com/zeroc/icestorm/3.6.1/icestorm-3.6.1.pom
