usr/bin/slice2cpp
usr/share/man/man1/slice2cpp.1

usr/include/*

usr/lib/*/libGlacier2CryptPermissionsVerifier.so
usr/lib/*/libGlacier2.so
usr/lib/*/libIce.so
usr/lib/*/libIceBox.so
usr/lib/*/libIceBT.so
usr/lib/*/libIceDB.so
usr/lib/*/libIceDiscovery.so
usr/lib/*/libIceGrid.so
usr/lib/*/libIceLocatorDiscovery.so
usr/lib/*/libIcePatch2.so
usr/lib/*/libIceSSL.so
usr/lib/*/libIceStorm.so
usr/lib/*/libIceUtil.so
usr/lib/*/libIceXML.so
usr/lib/*/libSlice.so

usr/lib/*/c++11/*
