#!/bin/sh

# **********************************************************************
#
# Copyright (c) 2003-present ZeroC, Inc. All rights reserved.
#
# **********************************************************************

exec java -cp `build-classpath icegridgui` com.zeroc.IceGridGUI.MainProxy $@
