#!/bin/sh

# **********************************************************************
#
# Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
#
# **********************************************************************

exec java -cp `build-classpath icegridgui` IceGridGUI.MainProxy $@
