usr/lib/*/libIce.a
usr/lib/*/libGlacier2.a
usr/lib/*/libIceGrid.a
usr/lib/*/libIceStorm.a

usr/lib/*/libIceUtil.so
usr/lib/*/libIce.so
usr/lib/*/libIceDiscovery.so
usr/lib/*/libIceSSL.so
usr/lib/*/libGlacier2.so
usr/lib/*/libIceGrid.so
usr/lib/*/libIceStorm.so
usr/lib/*/libSlice.so
usr/lib/*/libIceBox.so

usr/lib/*/libIceUtil.so.*
usr/lib/*/libIce.so.*
usr/lib/*/libIceDiscovery.so.*
usr/lib/*/libIceSSL.so.*
usr/lib/*/libGlacier2.so.*
usr/lib/*/libIceGrid.so.*
usr/lib/*/libIceStorm.so.*
usr/lib/*/libSlice.so.*
usr/lib/*/libIceBox.so.*